// Code generated by Slice Machine. DO NOT EDIT.

import ArticleWithImagesAndVideos from './ArticleWithImagesAndVideos';
import SimpleArticleSlice from './SimpleArticleSlice';

export {
	ArticleWithImagesAndVideos,
	SimpleArticleSlice,
};

export const components = {
	article_with_images_and_videos: ArticleWithImagesAndVideos,
	trending_article_main_body: SimpleArticleSlice,
};
